apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
data:
  # These are placeholders and will be replaced in the CI/CD pipeline
  # Base64 encoded values
  SUPABASE_URL: SUPABASE_URL_BASE64
  SUPABASE_ANON_KEY: SUPABASE_ANON_KEY_BASE64
  SUPABASE_SERVICE_ROLE_KEY: SUPABASE_SERVICE_ROLE_KEY_BASE64
  AUTH_SERVICE_DATABASE_URL: AUTH_SERVICE_DATABASE_URL_BASE64
  M2M_JWT_SECRET_KEY: M2M_JWT_SECRET_KEY_BASE64
  REDIS_URL: REDIS_URL_BASE64
  BASE_URL: BASE_URL_BASE64
  USE_PGBOUNCER: ZmFsc2U=  # Base64 encoded value of 'false'
