services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/app/docker-entrypoint.sh"]
    environment:
      - DATABASE_URL=${AUTH_SERVICE_DATABASE_URL:-postgresql+psycopg://user:password@db_auth/authdb}
      - TEST_DATABASE_URL=postgresql+psycopg://postgres:postgres@supabase_db_paauth:5432/postgres
      - USE_PGBOUNCER=true
      - LOGGING_LEVEL=DEBUG
      - PIP_DEFAULT_TIMEOUT=300
      - SUPABASE_URL=http://supabase_kong_paauth:8000
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your_default_secret_key_for_testing}
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000" # Exposes auth_service on host port 8000
    env_file:
      - .env.dev
    volumes:
      # Mount the application source code
      # This maps your local ./src directory to /app/src in the container
      - ./src:/app/src
      # Mount the tests directory
      - ./tests:/app/tests
      # Mount the test_migrations directory
      - ./test_migrations:/app/test_migrations
    networks:
      - supabase_project_network

networks:
  supabase_project_network:
    name: supabase_network_paauth
    external: true
