# k8s/migration-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: auth-service-migrations
  labels:
    app: auth-service
    component: migrations
spec:
  template:
    metadata:
      labels:
        app: auth-service
        component: migrations
    spec:
      containers:
        - name: auth-service-migrator
          image: ${DOCKER_IMAGE_TAG}
          # --- CORRECTED COMMAND ---
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "=== Starting Auth Service database migration job ==="
              # The PYTHONPATH is already set in the new Dockerfile, but being explicit here is safe.
              export PYTHONPATH=/app/src:$PYTHONPATH
              echo "PYTHONPATH is: $PYTHONPATH"

              echo "Executing Alembic..."

              ALEMBIC_STATUS=$?
              if [ $ALEMBIC_STATUS -ne 0 ]; then
                echo "Alembic command failed with status $ALEMBIC_STATUS. Container will sleep for 60s for log retrieval."
                sleep 60
                exit $ALEMBIC_STATUS
              fi
              echo "Migration completed successfully."
          envFrom:
            - secretRef:
                name: paservices-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      restartPolicy: Never
      # Add a reasonable timeout for the job
      activeDeadlineSeconds: 900 # 15 minutes timeout for the entire job
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600
