apiVersion: batch/v1
kind: Job
metadata:
  name: super-id-service-migration
  labels:
    app: super-id-service
    component: migration
spec:
  backoffLimit: 2  # Retry twice before failing
  activeDeadlineSeconds: 600  # Time limit 10 minutes
  template:
    metadata:
      labels:
        app: super-id-service
        component: migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: super-id-service-migration
          image: ${DOCKER_IMAGE_TAG}
          command:
            - sh
            - -c
            - |
              echo "Running database migrations for Super ID Service..."
              echo "Using dedicated database for proper service isolation..."
              cd /app
              
              # Print environment info for debugging
              echo "Checking environment variables:"
              echo "ENVIRONMENT is: $ENVIRONMENT"
              echo "SUPER_ID_SERVICE_SUPABASE_URL exists: $([ ! -z "$SUPER_ID_SERVICE_SUPABASE_URL" ] && echo "yes" || echo "no")"
              echo "SUPER_ID_SERVICE_SUPABASE_SERVICE_ROLE_KEY exists: $([ ! -z "$SUPER_ID_SERVICE_SUPABASE_SERVICE_ROLE_KEY" ] && echo "yes" || echo "no")"
              echo "SUPER_ID_SERVICE_DATABASE_URL exists: $([ ! -z "$SUPER_ID_SERVICE_DATABASE_URL" ] && echo "yes" || echo "no")"
              
              # Execute migrations using Alembic from the super_id_service directory
              cd super_id_service && poetry run alembic upgrade head
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: LOG_LEVEL
              value: "INFO"
            - name: ENVIRONMENT
              value: "production"
            - name: SUPER_ID_SERVICE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: super-id-service-secrets
                  key: SUPER_ID_SERVICE_DATABASE_URL
            - name: SUPER_ID_SERVICE_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: super-id-service-secrets
                  key: SUPER_ID_SERVICE_SUPABASE_URL
            - name: SUPER_ID_SERVICE_SUPABASE_SERVICE_ROLE_KEY
              valueFrom:
                secretKeyRef:
                  name: super-id-service-secrets
                  key: SUPER_ID_SERVICE_SUPABASE_SERVICE_ROLE_KEY
            - name: SUPER_ID_SERVICE_M2M_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: super-id-service-secrets
                  key: SUPER_ID_SERVICE_M2M_JWT_SECRET_KEY
            # Configure database options with proper format (single quotes for values with spaces)
            - name: USE_PGBOUNCER
              value: "false"
            - name: DB_CONNECT_TIMEOUT
              value: "60"
            - name: DB_COMMAND_TIMEOUT
              value: "60"
            - name: DB_STATEMENT_TIMEOUT
              value: "0"  # No timeout for long operations
            - name: DB_IDLE_TIMEOUT
              value: "180"  # 3 minutes idle timeout
            - name: DB_POOL_SIZE
              value: "10"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      terminationGracePeriodSeconds: 30
