apiVersion: v1
kind: Secret
metadata:
  name: super-id-service-secrets
type: Opaque
data:
  SUPABASE_URL: SUPABASE_URL_BASE64
  SUPABASE_SERVICE_ROLE_KEY: SUPABASE_SERVICE_ROLE_KEY_BASE64
  M2M_JWT_SECRET_KEY: M2M_JWT_SECRET_KEY_BASE64
  SUPER_ID_SERVICE_DATABASE_URL: SUPER_ID_DATABASE_URL_BASE64  # postgresql://postgres.cbmjajenbnycseonudqx:5QCyIQUoU81NEkRU@aws-0-eu-north-1.pooler.supabase.com:5432/postgres
