services:
  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SUPER_ID_SERVICE_DATABASE_URL=postgresql+psycopg://postgres.cbmjajenbnycseonudqx:5QCyIQUoU81NEkRU@aws-0-eu-north-1.pooler.supabase.com:5432/postgres
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
